#!/bin/bash

unset UDOCKER_TARBALL

if [[ ! $UDOCKER_BASE ]]; then
  export UDOCKER_BASE=$PWD
fi

export UDOCKER_DIR=$UDOCKER_BASE/udocker
udocker_binary=$UDOCKER_BASE/bin/udocker

if [! -d $UDOCKER_BASE ]; then
  mkdir $UDOCKER_BASE
fi

mkdir -p $UDOCKER_BASE/bin
curl 'https://raw.githubusercontent.com/indigo-dc/udocker/devel/udocker.py' > $udocker_binary
chmod ugo+x $udocker_binary
$udocker_binary install

echo "export UDOCKER_DIR=$UDOCKER_DIR" > $UDOCKER_BASE/env.sh
echo "export PATH=$UDOCKER_BASE/bin:$UDOCKER_DIR/bin:$PATH" >> $UDOCKER_BASE/env.sh
echo "export PYENV_VERSION=toil" >> $UDOCKER_BASE/env.sh
